name = "PolyTech_1_20_1_forge"
author = "TouchTheGrassMan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b0b433d577902a4b5d5066632b17e50d670c0a2a9fa8cdc3834abf6abb3ef52"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
