name = "PolyTech_1_20_1_forge"
author = "TouchTheGrassMan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a0e5fc327eff8bfc5013c17a9ba9627a49adcb26265a892995a2d3773c3a6ff"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
