name = "PolyTech_1_20_1_forge"
author = "TouchTheGrassMan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8976e8cb428360fc80c192c641fde9e4b0adbcf15ea3777a5e7b4cebeda7121"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
