
["Улучшенные пустынные храмы YUNG'а"]

	###########################################################################################################
	## Общие настройки.
	###########################################################################################################
	["Улучшенные пустынные храмы YUNG'а".General]
		# Определяет, будут ли отключены ванильные пустынные пирамиды.
		# По умолчанию: true
		#
		"Отключить ванильные пустынные пирамиды" = true
		# Определяет, будет ли на игроков в пустынном храме накладываться усталость от копания, если храм ещё не был очищен.
		# По умолчанию: true
		#
		"Накладывать усталость от копания" = true

