
#Измените эти параметры, чтобы настроить клиентскую часть мода.
[Gameplay]
	#Разрешить вид от первого лица внутри трубы. По умолчанию отключено для более комфортной игры.
	allowFPVInsideTheTube = false

