#Шанс роста фруктов за случайный тик
#Range: 0.0 ~ 1.0
fruitsGrowChance = 0.1
#Шанс выпадения фруктов за случайный тик
#Range: 0.0 ~ 1.0
fruitsDropChance = 0.1
#Шанс увядания цветка после сбора/выпадения плодов
#Range: 0.0 ~ 1.0
flowerDecayChance = 0.1
#Шанс роста персика за случайный тик
#Range: 0.0 ~ 1.0
peachGrowChance = 0.1
#Шанс появления плода у персика после окончания цветения
#Range: 0.0 ~ 1.0
peachFruitChance = 0.3
#Шанс увядания персика при плодоношении
#Range: 0.0 ~ 1.0
peachDecayChance = 0.1
#Радиус применения эффекта «Аура ярости»
#Range: 0 ~ 64
rageEffectRange = 24
#Радиус применения эффекта «Аура исцеления»
#Range: 0 ~ 64
healEffectRange = 6
#Радиус применения эффекта «Отчуждение»
#Range: 0 ~ 64
alienatingEffectRange = 12
#Включить рецепты варенья и желе в котле
enableCauldronRecipe = true
#Включить совместимость с Thirst
enableThirstCompat = true

