#Показывать звучащую высоту на мутационных трубах при надетых очках.
displayMutationSoundingPitch = true
#Если включено, значения октав в подсказках очков показываются в скобках.
showOctaveBrackets = false

