#Шанс появления частицы дыма. 1.0 - максимум, 0.0 - дыма нет. По умолчанию: 0.75
#Range: 0.0 ~ 1.0
SmokeFlow = 0.75
#Дымоходы коптятся при случайном тике. Дымоход должен работать (LIT) и не быть 'BLOCKED'
#а при случайном тике это значение задаёт шанс закопчения дымохода.
#1.0 - закоптится при первом случайном тике.
#0.0 - дымоход никогда не закоптится.
#Default: 0.05
#Range: 0.0 ~ 1.0
DirtyChance = 0.05
#Частицы дыма зависят от ветра. По умолчанию: true
Wind = true
#Насколько сильно ветер влияет на дым. По умолчанию: 1.0
#Range: 0.0 ~ 1.7976931348623157E308
WindStrength = 1.0
#Ветер влияет на дым от костров. По умолчанию: true
WindAffectsCampfire = true

