
[spawn-general]
	#Прозрачность мух от первого лица; 0 — отключить.
	#Range: 0.0 ~ 1.0
	first_person_fly_opacity = 1.0
	#Показывать ли более светлую воду выше уровня моря в биомах из тега (по умолчанию только приливные лужи). Можно отключить ради производительности.
	lighter_inland_water_for_tagged_biomes = true

[bucket-changes]
	#Показывать ли содержимое мобов в ведре в подсказке.
	bucket_tooltip = true

